pull_request_rules:
  - name: automatic merge on approval and CI pass
    conditions:
      - '#approved-reviews-by>=1'
      - status-success=AxaGuilDEv.react-toolkit
      - status-success=SonarCloud Code Analysis
      - label!=WIP
    actions:
      merge:
        method: squash
