export default {
  pathSrc: './src',
  pathDest: './dist',
  pathImg: 'assets/images',
  pathImgDist: '/assets',
  pathFavicons: '/assets/favicons',
  jsFiles: '/**/*.js',
  sassIndex: '/index.scss',
  sassFiles: '/**/*.scss',
  pugFiles: '/**/*.pug',
  componentsPugFiles: '/components/**/*.pug',
  commonsPugFiles: '/commons/**/*.pug',
  pugWatchFiles: '/**/**/*.pug',
  jsonPageFiles: '/pages/**/*.json',
  jsonFiles: '/data/*.json',
  pathSvg: '/assets/icons',
  svgFiles: '/*.svg',
  pathSprite: '/assets/sprite',
  pathImgFiles: '/assets/images',
  imgFiles: '/*.{jpg,jpeg,svg,gif,png}',
  pathFontToolkit: './node_modules/@axa-fr/react-toolkit-core/dist/assets/fonts/icons',
};
