# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    git config --global user.email "build-ci@axa.fr"
    git config --global user.name "Build-CI"
    node ./scripts/publish.js $(Github.Token)
  displayName: 'publish website'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))


