name: Compatibility npm on multi OS & Node version

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
      - release/**

jobs:
  setup:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14, 15]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@v2

      - run: npm ci
      - run: npm test
