name: Publish pre-release version to npm registry

on: workflow_dispatch
# No push trigger events because PAT, use here, will do a recursive workflow run

env:
  NODE_VERSION: 16.x

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'AxaGuilDEv'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_PAT }}
      - name: Use Node.js specific version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run check
      - run: |
          git config user.name "Build-CI"
          git config user.email build-ci@axa.fr
      - name: Create new pre release
        run: npx lerna version prerelease --exact --force-publish --yes
      - name: Publish pre-release packages to npm
        run: npx lerna publish from-git --dist-tag next --yes --registry https://registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
