name: Publish Toolkit packages to Npm registry

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  NODE_VERSION: 14.x
  STORYBOOK_BUILD: storybook-static

jobs:
  publish:
    environment:
      name: Release
    runs-on: ubuntu-latest
    outputs:
      isPreRelease: ${{ steps.release_var.outputs.isPreVersion }}
      releaseVersion: ${{ steps.release_var.output.version}}
    steps:
      - name: Set release version variable
        id: release_var
        run: |
          version=${GITHUB_REF#refs/tags/v}
          echo "::set-output name=version::$version"
          isPreVersion=$([[ "$version" != "${version#*"-"}" ]] && echo true || echo false)
          echo "it's a pre release: $isPreVersion"
          echo "::set-output name=isPreRelease::$isPreVersion"
      - uses: actions/checkout@v2
      - name: Use Node.js specific version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run check
      - run: npm test -- --coverage
      - name: Build storybook
        if: ${{ steps.release_var.outputs.isPreRelease == false }}
        run: npm run storybook:build
      - name: Upload Storybook into workflow artifact
        if: ${{ steps.release_var.outputs.isPreRelease == false }}
        uses: actions/upload-artifact@v2
        with:
          name: storybook
          path: ${{env.STORYBOOK_BUILD}}
      - name: Publish pre-release packages to npm
        if: ${{ steps.release_var.outputs.isPreRelease == true }}
        run: npx lerna publish from-git --dist-tag next --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish release packages to npm
        if: ${{ steps.release_var.outputs.isPreRelease == false }}
        run: npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-storybook:
    runs-on: ubuntu-latest
    needs: publish
    if: ${{ needs.publish.outputs.isPreRelease == false }}
    env:
      RELEASE_VERSION: ${{ needs.publish.outputs.releaseVersion }}
    defaults:
      run:
        working-directory: gh-pages/react-toolkit
    outputs:
      previousVersion: ${{ steps.rename-latest-storybook.outputs.prevVersion }}
    steps:
      - name: Checkout Axa Github Pages
        uses: actions/checkout@v2
        with:
          repository: AxaGuilDEv/AxaGuilDEv.github.io
          ref: master
          path: gh-pages
      - name: Rename latest Storybook folder
        id: rename-latest-storybook
        run: |
          prevVersion=`node -p "require('./latest/version.json').version"`
          mv latest v$prevVersion
          echo "::set-output name=prevVersion::$prevVersion"
      - uses: actions/download-artifact@v2
        with:
          name: storybook
          path: gh-pages/react-toolkit
      - name: Add version json file into latest
        run: |
          mv $STORYBOOK_BUILD latest
          echo {\"version\":\"$RELEASE_VERSION\"} >> ./latest/version.json
      - name: Commit changes
        run: |
          git config user.name "Build-CI"
          git config user.email build-ci@axa.fr
          git add .
          git commit –message "doc(toolkit): publish storybook v$RELEASE_VERSION"
          git push

  release-gh:
    runs-on: ubuntu-latest
    needs: [publish, deploy-storybook]
    if: ${{ needs.publish.outputs.isPreRelease == false }}
    env:
      PREVIOUS_VERSION: ${{ needs.deploy-storybook.outputs.previousVersion }}
      RELEASE_VERSION: ${{ needs.publish.outputs.releaseVersion }}
    steps:
      - uses: actions/checkout@v2
      - name: Create changelog
        id: create-changelog
        run: |
          git fetch --all --tags
          changelog=$(git log v$PREVIOUS_VERSION...v$RELEASE_VERSION --pretty=format:'- %s _by %aN_')
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=CHANGELOG::$changelog"
      - name: Create Github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: |
            ${{ steps.create-changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
